# 公開するページのURL
baseURL = "https://fairy-lettuce.github.io/fairy-lettuce-blog"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "Growth Record of Lettuce Farm: Extended"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "れたす"
    bio = "ゆるふわ情報系心理学徒みならい"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#ed8a34"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "fairy_lettuce"
  github = "fairy-lettuce"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

